main: net.cdx.bonusround.Main
version: 1.0.0
name: BonusRound
author: CDX
api-version: 1.20
commands:
  help:
    permission: commands.default.help
soft depend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot