main: net.cdx.bonusround.Main
version: 1.0.0
name: BonusRound
author: CDX
api-version: 1.20
soft depend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.18.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.18.0