main: net.bonusround.game.Main
version: 1.0.0
name: BonusRound
author: CDX
api-version: 1.20
commands:
  help:
    permission: commands.default.help
soft depend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
libraries:
  - net.dv8tion:JDA:5.0.1
  - club.minnced:discord-webhooks:0.8.4